title: Crooked Arrow Tattoo
description: The Tattoo Shop of West Point
url: crookedarrowtattoo.com
facebook:
  publisher:
logo: /assets/logo.png

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  -jekyll-seo-tag
